### ISSUE TITLE
group/nest by @media/@supports

### ISSUE THREAD

**Issue by threepointone** [threepointone/bs-nice#4]
eg - 
```css
@media screen {
  .css-1X8pjt {
    display: block;
    color: green;
  }
}
@media screen {
  .css-1X8pjt:hover {
    color: orange;
    font-weight: bold;
    overflow: hidden;
  }
}
@media screen {
  @supports (display: flex) {
    .css-1X8pjt:hover {
      color: blue;
    }
  }
}
```
should be
```css
@media screen {
  .css-1X8pjt {
    display: block;
    color: green;
  }
  .css-1X8pjt:hover {
    color: orange;
    font-weight: bold;
    overflow: hidden;
  }
  @supports (display: flex) {
    .css-1X8pjt:hover {
      color: blue;
    }
  }

}
```
